artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://raw.githubusercontent.com/neustackapp/assignment/refs/heads/main/employee_data.csv
  local_data_file: artifacts/data_ingestion/employee_data.csv
 

data_validation:
  root_dir: artifacts/data_validation
  validation_dir: artifacts/data_validation/data
  unzip_data_dir: artifacts/data_ingestion/employee_data.csv
  STATUS_FILE: artifacts/data_validation/status.txt

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts\data_validation\data\preprocessed_data.csv
  

model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: "logistic_regression_model.pkl"
  cv_folds: 3
  scoring_metric: "accuracy"

model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test.csv
  model_path: artifacts/model_trainer/logistic_regression_model.pkl
  metric_file_name: artifacts/model_evaluation/metrics.json

mlflow_info:
  tracking_uri: https://dagshub.com/archanalonkar/assignmen_solution.mlflow
  tracking_username: archanalonkar
  tracking_password: 799d5c2ca62fdceb37551730c817faa20a64b990